[package]
name = "adventure-land"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.3"
regex = "^1.6"
dirs = "4.0.0"

[dependencies.rand]
version = "0.8.5"
features = ["std_rng"]
