#+title: List of items that would be useful in the project

* General Ideas
** TODO support nested adventures
Currently, all adventures need to be within books folder, I want the capture process also consider any subfolder that isn't adventure for capturing.

Main benefit for this would be to allow storing multiple adventures within a git repository to have collections of stories.
** TODO Conditional text in pages
Would be cool to have text be tied to a condition so pages would be capable of displaying different text based on whatever a condition is met or not

Maybe use the existing [] tags and structure it like [if condition-name: text to display]?
** TODO Dummy choice in pages
If a page doesn't have any choices declared, the game should create a dummy choice allowing player to exit to menu as page like that would be considered a game over screen.
* Editor
** TODO Error checker
There need to be some way to automatically check for any issues or unused elements in the pages.
** TODO Autosave
There are situations where the program may close unexpectedly. Every save operation should be committed to drive to prevent loss of work.
* Known issues
** FIXME Titles in play mode are not displayed
** FIXME Variable editors don't rescale properly
